### ISSUE TITLE
weinig `h1` elementen in `section`

### ISSUE THREAD

**Issue by SamaraFellaDina** [koeenm/the-startup-responsive-interactieve-website#5]
![image](https://github.com/koeenm/the-startup-responsive-interactieve-website/assets/144009778/99392671-2cc4-4821-a3f0-68bab958a694)

Niet elke section heeft een `h1` of `h2` element kan je daarvoor een `div` gebruiken wanneer je geen header nodig hebt

**Comment by koeenm** [comment]
hoi ik heb er een div van gemaakt !!
