### ISSUE TITLE
`img: src` heeft geen goede source

### ISSUE THREAD

**Issue by SamaraFellaDina** [koeenm/the-startup-responsive-interactieve-website#6]
![image](https://github.com/koeenm/the-startup-responsive-interactieve-website/assets/144009778/1c83ee57-6a86-4e1f-9010-feb79d45a681)

`the-daily-move-(live radio).avif" alt="the daily move` heeft geen goede naam, omdat er spaties in zitten. 

https://github.com/koeenm/the-startup-responsive-interactieve-website/blob/d719756b2dc5fce6a90fc5fc2b7cf7897bc6bbce/index.html#L84

Je kan beter vervangen door: `the-daily-move-(live-radio).avif`

![](https://media.giphy.com/media/ImbwId9FR3gkg/giphy.gif)

**Comment by koeenm** [comment]
hoi ik heb dit opgelost op de manier die je voorstelde

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWExM2dpM251YWNzcWZ3NGt4N3E4ZzhmdTh4OHU3eDdwOWwwODBpdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Hrzm84HQeT3XrtZDK0/giphy.gif)
